# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
dist: trusty
cache: packages
latex: false
fortran: true

jobs:
  include:
  - os: osx
  - r: devel
  - r: release
  - r: 3.4
  - r: 3.3
  after_success:
    - Rscript -e 'covr::codecov()'
    deploy:
      skip_cleanup: true
    warnings_are_errors: true
    env:
      - DEVEL_PACKAGES=true
    # r_packages:
    #   - Rcpp
    #   - dplyr
    #   - ggplot2

matrix:
  fast_finish: true
  # allow_failures:
  # - env: DEVEL_PACKAGES=true
