# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - release
  - devel
os:
  - linux
  - osx
  - windows
warnings_are_errors: false # Don't fail build; change to true when ready to submit to CRAN
cache:
  packages: true # Cache packages to reduce build times
latex: true
after_success:
  - Rscript -e 'covr::codecov()'
fast_finish: true
